version: 2.1

jobs:
  beta-android:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run: bash scripts/beta.sh

workflows:
  beta:
    jobs:
      - beta-android