version: 2.1

jobs:
  try-job:
    macos:
      xcode: "14.0.1"
    steps:
      - run: echo "I am a job named essam Mohamed within workflow named try-workflow"

workflows:
  try-workflow:
    jobs:
      - try-job