  version: 2.1
  jobs:
    try-job:
      steps:
        - run: echo "I am try a job named try job within a work flow named try-workflow"


  workflows:
    try-workflow:
      jobs:
        - try-job