# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    print "fastlane worked successfully"
   end

   desc "prepare Android Debug Build"
   lane :build_debug_android do
   gradle(
     task: "assembleDebug",
   )
   end

    desc "prepare Android Release Build"
      lane :build_release_android do
      gradle(
        task: "assembleRelease",
      )
      end


    desc "prepare Android  Build & Distribute to Firebase App Distribution"
      lane :beta_android do
      build_release_android
      firebase_app_distribution(
          app: "1:927341947557:android:238c401c437c7ec0367b4c",
          firebase_cli_token: "1//03VmgA44tzbx2CgYIARAAGAMSNwF-L9IrZ1XYz_HNE1eeQSZd8Dk7QdhRNndILZijrs_OdXTLP1ukzHo4rZh1y_XodLar9amgufk",
          groups:"testers"
      )
     end
 end


